### PR TITLE
Create `INSTALLDIR` in Make install target

### PR DESCRIPTION
**Pull request by paulmenzel**

### CODE REVIEW

**Comment by crash-utility** [comment]
I typically don't take github merge requests, but rather require that all proposed patches pass
through the crash-utility mailing list.  However, I will take the INSTALLDIR fix, but as far as the
trailing spaces, I don't really much care at this point.

Also, note that you made the patch to the configured version of the Makefile.  For any changes to
that file, you have to either use the virgin copy, or run "make unconfig", make a change, and then do
the diff.

Thanks,
  Dave

**Comment by crash-utility** [comment]
Also, can you give me an email address that I can put in the changelog?

**Comment by paulmenzel** [comment]
> Also, can you give me an email address that I can put in the changelog?

pmenzel@molgen.mpg.de

**Comment by crash-utility** [comment]
Thanks -- checked in...

**Pull request closed without merging**
