### PR TITLE
Check a file is opened

### PR DESCRIPTION
**Pull request by raminfp**

### CODE REVIEW

**Comment by crash-utility** [comment]
Hello Ramin,

Normally patches to the crash utility should be posted to
the crash-utility@redhat.com mailing list for a general
review, as I don't ever do a "git pull" directly of a
github request.  But this one is pretty obvious, so Ill
apply it.

For the release changelog entry, however, can you show exactly 
what happens during initialization?  Does it fail quietly, cause
a SIGSEGV, or just complain that the file is "not a supported
file format"?

Thanks,
  Dave


----- Original Message -----

**Comment by raminfp** [comment]
Thanks Dave, just check if file format isn't exist,

**Comment by crash-utility** [comment]
----- Original Message -----
> Thanks Dave, just check if file format isn't exist,

Ok, so for example, if I make the vmcore file unreadable, I see this
cascade of error messages:

  $ crash vmlinux vmcore
  ...
  vmcore: ELF header read: Permission denied
  vmcore: ELF header read: Permission denied
  crash: vmcore: lseek: Invalid argument
  read_maps: unable to read header from vmcore, errno = 0
  crash: sadump: cannot read dump device
  crash: sadump: cannot read partition header
  crash: vmw: Failed to read 'vmcore': [Error 13] Permission denied
  crash: vmcore: not a supported file format

  Usage:
  ...

So as I understand it, with your patch, there will just be another line
in addition to the above.

Dave



>

**Comment by crash-utility** [comment]
Note: I'm not going change is_390_dump() to exit, but rather I'm going
to add its error message to the others, and return FALSE.

Dave

----- Original Message -----

**Comment by raminfp** [comment]
Ok, where is your commit?

**Comment by raminfp** [comment]
Cool, Thanks,

**Pull request closed without merging**
