### PR TITLE
Fix to handle negative value to option phys_base=

### PR DESCRIPTION
**Pull request by santoshx**
I assumed lot of things here.
Please feel to amend it to your perfection.

### CODE REVIEW

**Comment by santoshx** [comment]
Without this negative values are simply ignored with a warning:

WARNING: ignoring --machdep option: phys_base=-308281344

**Comment by crash-utility** [comment]
I see the problem, but your patch removes a couple of possibilities.  I don't want to remove the capability of appending "m" or "M" for a decimal number of megabytes, nor do I want to remove the capability of entering a hexadecimal number that is not preceded by "0x". 

BTW, I never do pull requests, but rather all external patches should normally be posted on the crash
utility mailing list at: https://www.redhat.com/mailman/listinfo/crash-utility

So anyway, let me tinker around with your patch and come up with a solution that covers all bases.

Thanks,
   Dave

**Comment by crash-utility** [comment]
Thanks Santosh,
   https://github.com/crash-utility/crash/commit/fee99ccfd2fb3605c4392e8d8fb22fedb39c743c
Dave

**Comment by santoshx** [comment]
Thank you for quick help Dave!

**Pull request closed without merging**
