### PR TITLE
B xen bug

### PR DESCRIPTION
**Pull request by jpdonnell**
Author: John Donnelly <john.p.donnelly@oracle.com>
Date:   Thu Apr 8 10:18:10 2021 -0700

    add paravirt_patch_default lookup
    
    The upstream kernel commit edcb5cf84f05e5d2e2af25422a72ccde359fcca9
    "x86/paravirt/xen: Remove xen_patch()" broke crash compatibility
    This change adds a check for both symbols: "xen_patch" and
    it's replacement: "paravirt_patch_default".
    

This is just for kernel.c 

Ignore the other files.

### CODE REVIEW

**Comment by lian-bo** [comment]
Hi, @jpdonnell 
Can you subscribe the crash utility mail list and post this patch to crash-utility@redhat.com?
subscribe: https://listman.redhat.com/mailman/listinfo/crash-utility
post your patch: crash-utility@redhat.com

This change looks good to me. Thanks.

**Comment by k-hagio** [comment]
@lian-bo, sorry I said that a pull request would be fine in #78 because it's simple enough.
Can we review this patch here?

**Comment by lian-bo** [comment]
> @lian-bo, sorry I said that a pull request would be fine in #78 because it's simple enough.
> Can we review this patch here?
Sure. I think this patch is good, I can ack it. If it is easy to deal with,  you could merge this one here.
Thank you, @k-hagio and @jpdonnell .

**Comment by jpdonnell** [comment]
> > @lian-bo, sorry I said that a pull request would be fine in #78 because it's simple enough.
> > Can we review this patch here?
> > Sure. I think this patch is good, I can ack it. If it is easy to deal with,  you could merge this one here.
> > Thank you, @k-hagio and @jpdonnell .

Hi.


Thank you..

Have you considered forwarding a pull request to the crash-email dlist ?  I've seen other projects that do that.

**Comment by lian-bo** [comment]
> > > @lian-bo, sorry I said that a pull request would be fine in #78 because it's simple enough.
> > > Can we review this patch here?
> > > Sure. I think this patch is good, I can ack it. If it is easy to deal with,  you could merge this one here.
> > > Thank you, @k-hagio and @jpdonnell .
> 
> Hi.
> 
> Thank you..
> 
> Have you considered forwarding a pull request to the crash-email dlist ? I've seen other projects that do that.
Thanks for your suggestions. @jpdonnell. Let me have a try. @crash-utility

**Comment by k-hagio** [comment]
Hi @jpdonnell,

One question, do you know whether we should do the same change in x86_64.c and x86.c below?
```
$ git grep xen_patch
kernel.c:           STREQ(p1, "xen_patch")) {
x86.c:  if (symbol_exists("pv_init_ops") && symbol_exists("xen_patch") &&
x86_64.c:       if (symbol_exists("pv_init_ops") && symbol_exists("xen_patch") &&
```
i.e.
```
-       if (symbol_exists("pv_init_ops") && symbol_exists("xen_patch") &&
+       if (symbol_exists("pv_init_ops") && (symbol_exists("xen_patch") || symbol_exists("paravirt_patch_default")) &&
```

> Have you considered forwarding a pull request to the crash-email dlist ? I've seen other projects that do that.

Thanks, will consider.

**Comment by jpdonnell** [comment]
> Hi @jpdonnell,
> 
> One question, do you know whether we should do the same change in x86_64.c and x86.c below?
> 
> ```
> $ git grep xen_patch
> kernel.c:           STREQ(p1, "xen_patch")) {
> x86.c:  if (symbol_exists("pv_init_ops") && symbol_exists("xen_patch") &&
> x86_64.c:       if (symbol_exists("pv_init_ops") && symbol_exists("xen_patch") &&
> ```
> 
> i.e.
> 
> ```
> -       if (symbol_exists("pv_init_ops") && symbol_exists("xen_patch") &&
> +       if (symbol_exists("pv_init_ops") && (symbol_exists("xen_patch") || symbol_exists("paravirt_patch_default")) &&
> ```
> 
> > Have you considered forwarding a pull request to the crash-email dlist ? I've seen other projects that do that.
> 
> Thanks, will consider.

Hi, 

wrt to x86 .. I think so. I haven't used a x86 (32 bit ) kernel in over a decade. Most distros have stopped producing x86 too. I don't have a means to test it but if think it is appropriate go ahead. 



Thank you. 

John.

**Comment by k-hagio** [comment]
Thanks for the quick response, John.  Will add the fixes.

**Pull request closed without merging**
